- name: Update APT packages
  apt:
    update_cache: yes
    upgrade: full
  tags: apt

- name: Install software
  apt:
    name:
      - tmux
      - htop
      - rsync
    state: present
  tags: apt

- name: Set the host name
  hostname:
    name: wordclock

- name: Copy the public key of the user who is running ansible to the remote machine
  authorized_key:
    user: pi
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags: ssh

- name: Start the ssh service
  systemd:
    name: ssh
    state: started
    enabled: true

- name: No stupid login message
  file:
    path:  /home/pi/.hushlogin
    state: touch
    owner: pi
    group: pi
    mode:  "0755"

- name: Set keyboard layout to DE
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
