- name: APT packages are up-to-date
  apt:
    update_cache: yes
    upgrade: full
  become: true
  tags: apt

- name: Common software is installed
  apt:
    name:
      - tmux
      - htop
      - rsync
      - i2c-tools
    state: present
  become: true
  tags: apt

- name: Public key of the user who is running ansible is present at the remote machine
  authorized_key:
    user: pi
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags: ssh

- name: SSH service is started
  systemd:
    name: ssh
    state: started
    enabled: true
  become: true

- name: Stupid login message is disabled
  file:
    path:  /home/pi/.hushlogin
    state: touch
    owner: pi
    group: pi
    mode:  "0755"

- name: Keyboard layout is set to DE
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
  become: true
