- name: Update APT packages
  apt:
    update_cache: yes
    upgrade: yes
  tags: apt

- name: Set the host name
  hostname:
    name: "{{ inventory_hostname }}"

- name: No stupid login message
  file:
    path:  /home/pi/.hushlogin
    state: touch
    owner: pi
    group: pi
    mode:  "0755"

- name: Install software
  apt:
    name:
      - tmux
      - htop
      - rsync
    state: present
  tags: apt
