# Until we have a daemon, we launch via cron

- cron:
    env: yes
    user: pi
    name: PATH
    value: "/usr/local/bin:/usr/bin:/bin"
  tags: cron

- cron:
    env: yes
    user: pi
    name: BUNDLE_GEMFILE
    value: "{{ ansistrano_deploy_to }}/current/Gemfile"
  tags: cron

- cron:
    user: pi
    name: "Update time at wordclock"
    job: "bundle exec {{ ansistrano_deploy_to }}/current/exe/wordclock"
  tags: cron
