# Until we have a daemon, we launch via cron

- cron:
    env: yes
    user: pi
    name: PATH
    value: "/usr/local/bin:/usr/bin:/bin"
  tags: cron

- cron:
    env: yes
    user: pi
    name: BUNDLE_GEMFILE
    value: "/opt/word-clock/current/Gemfile"
  tags: cron

- cron:
    user: pi
    name: "Update time at word-clock"
    job: "bundle exec /opt/word-clock/current/exe/word-clock"
  tags: cron
