---
- name: Deploy word-clock
  hosts: all

  vars:
    # First-time setup without SSH keys deployed use this
    # ansible_ssh_user: pi
    # ansible_ssh_pass: raspberry

    ntp_timezone: Europe/Berlin
    ntp_manage_config: true
    ntp_servers:
     - ptbtime1.ptb.de iburst
     - ptbtime2.ptb.de iburst
     - ptbtime3.ptb.de iburst

    ruby_version:
      major: 2
      minor: 4
      revision: 1

    ansistrano_deploy_from: "{{ playbook_dir }}/.."
    ansistrano_deploy_to: "~/apps/word-clock"
    ansistrano_current_via: symlink
    ansistrano_deploy_via: rsync
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/word-clock/main.yml"

    unattended_origins_patterns:
      - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'
    unattended_automatic_reboot_time: "03:25"

    cups_admin_user: pi

    influxdb_database_name: sandbox
    influxdb_admin_password: d987f9fa4b08667ca683dbb

    telegraf_database: sandbox
    telegraf_password: d413891f0c3fb0bbbb8bb9
  roles:
    - common
    - wifi
    - fadecandy
    - geerlingguy.ntp
    - nerab.ruby
    - carlosbuenosvinos.ansistrano-deploy
    - jnv.unattended-upgrades
    - nerab.rsyslog-patch
    - nerab.airprint-server
    - influxdb
    - telegraf
    # - nats
