---
- name: Deploy wordclock
  hosts: all

  vars:
    # First-time setup without SSH keys deployed use this
    # ansible_ssh_user: pi
    # ansible_ssh_pass: raspberry
    hostname: wordclock

  roles:
    - role: nerab.raspi
      become: true
    - role: fadecandy
    - role: nerab.ruby
      vars:
        ruby_version:
          major: 2
          minor: 6
          teeny: 5
      tags: [ ruby ]
    - role: ansistrano.deploy
      vars:
        ansistrano_deploy_from: "{{ playbook_dir }}/.."
        ansistrano_deploy_to: "~/apps/wordclock"
        ansistrano_current_via: symlink
        ansistrano_deploy_via: rsync
        ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/wordclock/main.yml"
      tags: [ deploy, capistrano, ansistrano ]
    - role: jnv.unattended-upgrades
      become: true
      vars:
        unattended_origins_patterns:
          - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'
        unattended_automatic_reboot_time: "03:25"
      tags: [ apt, dpkg, update, upgrade ]
    - role: nerab.rsyslog-patch
    - role: ypsman.timedatectl
      become: true
      vars:
        timedatectl_timeservers:
          - ptbtime1.ptb.de
          - ptbtime2.ptb.de
          - ptbtime3.ptb.de
        timedatectl_timeservers_fallback:
          - 0.debian.pool.ntp.org
          - 1.debian.pool.ntp.org
        timedatectl_timezone: Europe/Berlin
      tags: [ time, date, ntp ]
    - role: dj-wasabi.telegraf
      vars:
        telegraf_agent_package_state: latest
        # https://github.com/dj-wasabi/ansible-telegraf#ansible_fqdn-problematic-for-getting-hostname
        telegraf_agent_hostname: "{{ ansible_nodename }}"
        telegraf_agent_output:
          - type: influxdb
            config:
              - urls = [ "https://influxdb.uhlig.it" ]
              - database = "metrics"
              - username = "wordclock"
              - password = "{{ telegraf_password }}"
      tags: [ telegraf, metrics ]
    - role: uhlig-it.ansible-role-mosquitto-bridge
      tags: [ mqtt, mosquitto ]
