---
- name: Deploy word-clock
  hosts: all
  become: true
  vars:
    ansible_user: pi
    ansible_ssh_pass: raspberry

    ntp_timezone: Europe/Berlin
    ntp_manage_config: true
    ntp_servers:
     - ptbtime1.ptb.de iburst
     - ptbtime2.ptb.de iburst
     - ptbtime3.ptb.de iburst

    ruby_version:
        full: ruby-2.3.3
        major: 2
        minor: 3
        revision: 3

    ansistrano_deploy_from: "{{ playbook_dir }}/.."
    ansistrano_deploy_to: /opt/word-clock
    ansistrano_current_via: symlink
    ansistrano_deploy_via: rsync
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/word-clock/main.yml"

    unattended_origins_patterns:
      - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'
    unattended_automatic_reboot_time: "03:25"

  roles:
    - common
    - wifi
    - ruby
    - fadecandy
    - geerlingguy.ntp
    - carlosbuenosvinos.ansistrano-deploy
    - jnv.unattended-upgrades
    - nerab.rsyslog-patch
    - tersmitten.logrotated
