- name: Install prerequisite software
  apt:
    update_cache: yes
    name:
      - bash
      - bzip2
      - curl
      - build-essential
      - openssl
      - patch
      - tar
    state: present
  become: true
  tags: apt,ruby

- name: Download ruby-install
  get_url:
    url: https://github.com/postmodern/ruby-install/archive/v0.7.0.tar.gz
    dest: /tmp/ruby-install-0.7.0.tgz
  tags: ruby,ruby-install

- name: Unpack ruby-install
  unarchive:
    src: /tmp/ruby-install-0.7.0.tgz
    dest: /usr/local/src
    remote_src: yes
  become: true
  tags: ruby,ruby-install

- name: Install ruby-install
  command: make install
  args:
    chdir: /usr/local/src/ruby-install-0.7.0/
  become: true
  tags: ruby,ruby-install

- name: Install Ruby
  command: ruby-install --system ruby
  become: true
  tags: ruby,ruby-install
