---
- hosts: all
  become: true
  vars:
    ntp_timezone: Europe/Berlin
    ntp_manage_config: true
    ntp_servers:
     - ptbtime1.ptb.de iburst
     - ptbtime2.ptb.de iburst
     - ptbtime3.ptb.de iburst

    ruby_version:
        full: ruby-2.3.3
        major: 2
        minor: 3
        revision: 3

  roles:
    - common
    - wifi
    - ruby
    - fadecandy
    - geerlingguy.ntp
