---
- hosts: all
  become: true
  vars:
    ntp_timezone: Europe/Berlin
    ntp_manage_config: true
    ntp_servers:
     - ptbtime1.ptb.de iburst
     - ptbtime2.ptb.de iburst
     - ptbtime3.ptb.de iburst

  roles:
    - common
    - wifi
    - fadecandy
    - geerlingguy.ntp
