- name: Download tarball
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb-{{ influxdb_version }}_linux_armhf.tar.gz"
    dest: "/tmp/influxdb-{{ influxdb_version }}_linux_armhf.tar.gz"
  tags: influxdb

- name: Unpack tarball
  unarchive:
    src: "/tmp/influxdb-{{ influxdb_version }}_linux_armhf.tar.gz"
    dest: "/"
    remote_src: true
    extra_opts: "--strip-components=2"
  become: true
  tags: influxdb

# useradd --system -U -M influxdb -s /bin/false -d $DATA_DIR
- group:
    name: influxdb
    state: present
  become: true
  tags: influxdb

- user:
    name: influxdb
    group: influxdb
    system: true
    createhome: false
    home: /var/lib/influxdb
    shell: /bin/false
  become: true
  tags: influxdb

# chown -R -L influxdb:influxdb /var/lib/influxdb
- file:
    path: /var/lib/influxdb
    owner: influxdb
    group: influxdb
  become: true
  tags: influxdb

# chown -R -L influxdb:influxdb /var/log/influxdb
- file:
    path: /var/log/influxdb
    owner: influxdb
    group: influxdb
  become: true
  tags: influxdb

- name: Copy service definition file
  copy:
    src: /usr/lib/influxdb/scripts/influxdb.service
    dest: /lib/systemd/system/influxdb.service
    remote_src: true
  notify:
    - Restart Influxdb
  become: true
  tags: influxdb

# TODO Only run if auth is not on yet
- name: Create influxdb database
  shell: influx -execute "CREATE DATABASE sandbox"
  tags: influxdb

- name: Create admin user
  shell: influx -execute "CREATE USER admin WITH PASSWORD 'd987f9fa4b08667ca683dbb' WITH ALL PRIVILEGES"
  tags: influxdb

- name: Enable HTTP authentication
  ini_file:
    path: /etc/influxdb/influxdb.conf
    section: http
    option: "{{ item }}"
    value: true
  with_items:
     - enabled
     - auth-enabled
  notify:
    - Restart Influxdb
  become: true
  tags: influxdb

- name: Create gobot user with R/W access
  shell: "influx
            -username admin
            -password d987f9fa4b08667ca683dbb
            -execute \"CREATE USER gobot WITH PASSWORD 'bdf882e54c0fcb56ba25';
                       GRANT ALL ON sandbox TO gobot;\""
  tags: influxdb,gobot

- name: Create Grafana user with READ access only
  shell: "influx
            -username admin
            -password d987f9fa4b08667ca683dbb
            -execute \"CREATE USER grafana WITH PASSWORD 'e00b3fefc794ec68';
                       GRANT READ ON sandbox TO grafana\""
  tags: influxdb,grafana
